// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4MojLiHH22NRXWn0B7Ii6cY1NpsKzgxg',
    appId: '1:37800297873:web:8918b36663bee1f39bc630',
    messagingSenderId: '37800297873',
    projectId: 'proshorts-a4484',
    authDomain: 'proshorts-a4484.firebaseapp.com',
    storageBucket: 'proshorts-a4484.appspot.com',
    measurementId: 'G-D81G15PDFY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE3sslz4NznjulFs-MFZtQgqliyKRgICs',
    appId: '1:37800297873:android:b61426e091cd997f9bc630',
    messagingSenderId: '37800297873',
    projectId: 'proshorts-a4484',
    storageBucket: 'proshorts-a4484.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdtvVOPtnC-wbg1stnwYLjHauaDuEOd7E',
    appId: '1:37800297873:ios:d6abdf4ccdb9cf9d9bc630',
    messagingSenderId: '37800297873',
    projectId: 'proshorts-a4484',
    storageBucket: 'proshorts-a4484.appspot.com',
    iosClientId: '37800297873-vd2g3v4lbar7r39pjko70u5nfst01lb8.apps.googleusercontent.com',
    iosBundleId: 'com.example.proShorts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdtvVOPtnC-wbg1stnwYLjHauaDuEOd7E',
    appId: '1:37800297873:ios:d6abdf4ccdb9cf9d9bc630',
    messagingSenderId: '37800297873',
    projectId: 'proshorts-a4484',
    storageBucket: 'proshorts-a4484.appspot.com',
    iosClientId: '37800297873-vd2g3v4lbar7r39pjko70u5nfst01lb8.apps.googleusercontent.com',
    iosBundleId: 'com.example.proShorts',
  );
}
